Home/urls.py
from django.contrib import admin
from django.urls import path,include
from django.urls import path
from Home import views

app_name="Home"


urlpatterns = [

    path('', views.homepage, name="homepage"),
    path('detailed_view', views.detailed_view, name="detailed_view"),
    path('properties', views.properties, name="properties"),

]

Induspace/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static





urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('search/', include('Search.urls')),
    path('auth/', include('UserAuthentication.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Search/urls.py
from django.urls import path
from Search import views

app_name="Search"


urlpatterns = [

    path('search', views.search, name="search"),


]

UserAuthentication/urls.py
from django.urls import path
from UserAuthentication import views

app_name="UserAuthentication"


urlpatterns = [

    path('register', views.register, name="register"),
    path('reset', views.reset_password, name="reset_password"),
    path('login', views.user_login, name="login"),
    path('forgot', views.forgot_password, name="forgot_password"),
    path('logout',views.user_logout,name="logout"),

]

Home/models.py
from django.db import models

class Property(models.Model):
    # PROPERTY_CHOICES = [
    #     ('Apartment', 'Apartment'),
    #     ('Villa', 'Villa'),
    #     ('Independent House', 'Independent House'),
    #     ('Commercial Space', 'Commercial Space'),
    #     ('Land', 'Land'),
    # ]
    property_name = models.CharField(max_length=100)
    builder_name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    images = models.ImageField(upload_to='property_images/')
    city_name = models.CharField(max_length=100)
    area_range_sqft = models.IntegerField(default=0)
    bhk_range = models.IntegerField(default=1)
    floor_plan = models.ImageField(upload_to='floor_plans/')
    amenities = models.JSONField(default=dict)  # Providing an empty dictionary as the default value
    brief_about_property = models.TextField(default = 'NA')
    about_builder = models.TextField(default = 'NA')

    def __str__(self):
        return self.property_name

Search/models.py
from django.db import models

# Create your models here.

UserAuthentication/models.py
from django.db import models

# Create your models here.

Home/views.py
from django.shortcuts import render
from .models import Property

# Create your views here.

def homepage(request):
    return render(request,'home/homepage.html')


def detailed_view(request):
    return render(request,'home/detailed_view.html')

def properties(request):
    return render(request,'home/properties.html')

Search/views.py
from django.shortcuts import render

# Create your views here.

def search(request):
    return render(request,'search/search.html')

UserAuthentication/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages


# Create your views here.
def register(request):
    if(request.method=="POST"):
        u = request.POST['u']
        p = request.POST['p']
        p1 = request.POST['p1']
        e = request.POST['e']
        f = request.POST['f']
        l = request.POST['l']
        if(p==p1):
            u=User.objects.create_user(username=u,password=p,email=e,first_name=f,last_name=l)
            u.save()

            return redirect('UserAuthentication:login')  #appname:view

    return render(request,'userAuth/register.html')



def user_login(request):
    if (request.method == "POST"):
        u = (request.POST['u'])
        p = (request.POST['p'])
        user = authenticate(username=u, password=p)

        if user:
            login(request,user)
            return redirect('Home:landing')
        else:
            messages.error(request, "invalid credentials")
    return render(request,'userAuth/login.html')


def forgot_password(request):
    return render(request,'userAuth/forgot_password.html')


def reset_password(request):
    return render(request,'userAuth/reset_password.html')


def user_logout(request):
    logout(request)
    return user_login(request)

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device, initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />


</head>
<body>
<header>



<nav class="navbar navbar-expand-lg navbar-light bg-light mt-1" >
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a  class="nav-link active" aria-current="page" href="{% url 'Home:homepage' %}">Home</a>
        </li>

        <li class="nav-item dropdown" >
          <a  class="nav-link dropdown-toggle"  href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Category
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

            <li><a class="dropdown-item" href=""></a></li>


          </ul>
            </li>




            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href=""><i class="fa-solid fa-cart-shopping"></i></a>
        </li>




         </li>

           <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'UserAuthentication:logout' %}">Logout</a>
        </li>





            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'UserAuthentication:register' %}">Register</a>
        </li>



        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
         <a class="nav-link active" aria-current="page" href="{% url 'UserAuthentication:login' %}">
    Login
</a>





      </ul>





</div>
  <div class="ml-auto d-flex">
    <form class="form-inline">

      <div class="input-group">
        <input class="form-control" type="search" placeholder="Search your products" aria-label="Search">
        <div class="input-group-append">
          <button class="attractive-btn" type="submit">Search</button>
        </div>
      </div>

      </form>
    </div>
  </div>
</nav>


     </header>



{% block content %}
{% endblock %}

</body>
</html>

<!--<footer>-->
<!--    <div class="footer"  >-->
<!--        <i class="fa fa-copyright" area-hidden="true"></i> MyShop Private Limited All right Reserved</p>-->
<!--    </div>-->
<!--</footer>-->

templates/home/detailed_view.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}


<h1>this is detailed view</h1>



{% endblock %}

templates/search/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>this is search</h1>

</body>
</html>

templates/userAuth/forgot_password.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}


<h1>this is forgot password</h1>



{% endblock %}

templates/userAuth/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1> <center>Login Here</h1>

<form method="POST" class="myform">
  {% csrf_token %}

<div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter username">
</div>


<div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter password">
</div>


<div class="mb-3">
  <center>
    <input type="submit" class="attractive-btn" style="padding: 4px 70px;">
</div>

  </form>

{% if messages %}

<ul>
  {% for msg in messages %}
  <li>{{msg}}</li>
  {% endfor %}

</ul>
{% endif %}




{% endblock %}

templates/userAuth/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1><center>Register here</h1>


<form method="POST" class="myform">
  {% csrf_token %}

<div style="margin:10px;">


<div class="mb-3" ">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter your username">
</div>

<div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter your password">
</div>

<div class="mb-3">
  <label  class="form-label">Confirm Password</label>
  <input type="password" class="form-control" name="p1" placeholder="Confirm your password ">
</div>

<div class="mb-3">
  <label  class="form-label">First Name</label>
  <input type="text" class="form-control" name="f" placeholder="Enter your first name">
</div>

<div class="mb-3">
  <label  class="form-label">Last Name</label>
  <input type="text" class="form-control" name="l" placeholder="Enter your last name">
</div>

 <div class="mb-3">
  <label  class="form-label">Email</label>
  <input type="email" class="form-control" name="e" placeholder="Enter your e-mail address">
</div>


<div class="mb-3">
    <center>
    <input type="submit" class="attractive-btn" style="padding: 4px 70px;">
</div>

  </form>

</div>

{% endblock %}

templates/userAuth/reset_password.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}


<h1>this is reset password</h1>



{% endblock %}